pipeline {
    agent any
    environment {
        RELEASE = '20.04'
    }
    stages {
        stage('Build') {
            agent any
            environment {
                LOG_LEVEL='INFO'
            }
            steps {
                echo "Building release ${RELEASE} with log level ${LOG_LEVEL}..." 
                sh 'chmod +x demo2/build.sh'
                withCredentials([usernameColonPassword(credentialsId: 'test_id', variable: 'API_KEY')]) {
                    sh '''
                        /demo2/build.sh
                    '''
                }
            }
        }
        stage('Test') {
            steps {
                echo "Testing release ${RELEASE}..."
            }
        }
        stage('Deploy') {
            input {
                message 'Deploy?'
                ok 'Proceed'
                parameters {
                    string(name: 'TARGET_ENVIRONMENT', defaultValue: 'PROD', description: 'Target deployment environment')
                }
            }
            steps {
                echo "Deploying release ${RELEASE} to environment ${TARGET_ENVIRONMENT}"
            }
        }
    }
    post{
        success {
            emailext body: 'A successfull mail', subject: 'passed build', to: 'sk6434812@gmail.com' 
        }
        failure {
            emailext body: 'A failed build', subject: 'failure mail', to: 'sk6434812@gmail.com'
        }
    }    
}
